## 1. 실행 모드
executor: "KubernetesExecutor"

## 2. Web 서버에 호스트 볼륨 추가
web:
  extraVolumes:
    # DAGs
    - name: host-dags
      hostPath:
        path: /opt/airflow/dags
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: host-dags
      mountPath: /opt/airflow/dags

## 3. Scheduler에도 동일하게 마운트
scheduler:
  extraVolumes:
    - name: host-dags
      hostPath:
        path: /opt/airflow/dags
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: host-dags
      mountPath: /opt/airflow/dags

## 4. Worker (Triggerer 포함)에도 동일하게 마운트
workers:
  extraVolumes:
    - name: host-dags
      hostPath:
        path: /opt/airflow/dags
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: host-dags
      mountPath: /opt/airflow/dags

triggerer:
  extraVolumes:
    - name: host-dags
      hostPath:
        path: /opt/airflow/dags
        type: DirectoryOrCreate
  extraVolumeMounts:
    - name: host-dags
      mountPath: /opt/airflow/dags
