# values.yaml
executor: KubernetesExecutor       # K8s 위에선 K8sExecutor 추천
web:
  port: 8080
tolerations: []                    # 필요시 설정
persistence:
  enabled: true
  storageClass: standard
  accessMode: ReadWriteOnce
