
images:
  airflow:
    repository: apache/airflow
    tag: 2.10.5
    pullPolicy: IfNotPresent
  gitSync:
    repository: k8s.gcr.io/git-sync/git-sync
    tag: v3.8.2
    pullPolicy: IfNotPresent

executor: "KubernetesExecutor"

enableBuiltInSecretEnvVars:
  AIRFLOW__CORE__FERNET_KEY: true
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: true
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: true
  AIRFLOW_CONN_AIRFLOW_DB: true
  AIRFLOW__WEBSERVER__SECRET_KEY: true
  AIRFLOW__CELERY__CELERY_RESULT_BACKEND: true
  AIRFLOW__CELERY__RESULT_BACKEND: true
  AIRFLOW__CELERY__BROKER_URL: true
  AIRFLOW__ELASTICSEARCH__HOST: true
  AIRFLOW__ELASTICSEARCH__ELASTICSEARCH_HOST: true
  AIRFLOW__OPENSEARCH__HOST: true

# 1) persistence 끄기
dags:
  persistence:
    enabled: false
gitSync:
  enabled: false

logs:
  persistence:
    enabled: false

# 2) 루트 레벨 hostPath 볼륨 마운트 (모든 컴포넌트에 적용)
extraVolumes:
  - name: dags
    hostPath:
      path: /Users/jeremyshin/dev/airflow-k8s/dags

extraVolumeMounts:
  - name: dags
    mountPath: /opt/airflow/dags

